services:
  - type: web
    name: taskadmin
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    postDeployCommand: npm run migrate
    envVars:
      - key: DATABASE_URL
        sync: false
